### ISSUE TITLE
Index lost when adding new language

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#193] opened 2019-01-19 10:05 UTC
What we did:

* spin up new Hypha instance in English
* add a page and a mailing list (both in EN)
* add NL as a language
* set NL as default language
* **observe lost index in EN**

**Comment by dianawi** [comment] 2019-01-19 14:52
When I try it it comes back when you switch to English. It does not show anything in Dutch because there are no Dutch pages. So the index is correct.

**Comment by dianawi** [comment] 2019-01-19 14:59
aha, just saw on Harmen's hypha that his English index does disappear. maybe we can find out what the difference is between mine and his. Did you find the bug on your Hypha, Tammo, or on Harmen's?

**Comment by matthijskooijman** [comment] 2020-12-08 15:17
I just tried @tammoterhark's instructions and cannot reproduce this problem. I suspect it might be fixed by #311. I'm closing this, if it still exists, please reopen.

**Closed by matthijskooijman** 2020-12-08 15:17 UTC
