### ISSUE TITLE
Add mailing list gives error 500

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#76] opened 2018-09-27 09:19 UTC
Harmen: Turns out this only happens when the description is empty. Error log shows that a document without a documentElement is passed to wikifiy() which then crasehs.

Matthijs: @laurensmartina, can you have a look at this?

**Comment by matthijskooijman** [comment] 2019-01-17 08:32
I just tried this, and I cannot reproduced it. I tried adding a new mailinglist page with an empty description, as well as a new newsletter to an existing page. It seems it was fixed by c091abd, if I revert that, I can reproduce this error.

**Closed by matthijskooijman** 2019-01-17 08:32 UTC
Labels: Level: Easy
