### ISSUE TITLE
Email delivery fails if subject contains special characters

### ISSUE THREAD

**Issue by giplt** [PlanBCode/hypha#328] opened 2020-05-28 20:24 UTC
Some email providers send back messages from hypha that have utf-8 characters in their subject line. Below an example of the error message.
```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

SMTP error from remote mail server after end of data:
550 Subject contains invalid characters.
```

**Comment by matthijskooijman** [comment] 2020-05-28 20:42
This is a duplicate of #202, so I'm closing this in favor of that one.

**Closed by matthijskooijman** 2020-05-28 20:42 UTC

**Comment by giplt** [comment] 2020-05-28 20:54
Shoot, I had been looking for that one but searched on 'email' in stead of 'e-mail'.
